### ISSUE TITLE
"Drag and Drop" not working for Evidence "add files" box

### ISSUE THREAD

**Issue by tramserran-MathNerd101** [seahindeniz/BrainlyTools_Extension#107]
"Drag and drop" screenshots in the "add files" box under EVIDENCES is not working
![Screen Shot 2020-04-01 at 1 28 03 AM](https://user-images.githubusercontent.com/62987067/78115975-73ab3c00-73b8-11ea-85b9-ef31ca589ce4.png)

**Comment by seahindeniz** [comment]
On the next release, evidence form will be a little bit different and it will have drag and drop support.

![image](https://i.ibb.co/jJg70Bz/formsample.gif)
