### ISSUE TITLE
Breaking changes in brainly style-guide

### ISSUE THREAD

**Issue by matzimowski** [seahindeniz/BrainlyTools_Extension#109]
@seahindeniz fyi, we are planning to do a renaming of `Button` component modifiers in coming day (i.e from `--primary` to `--solid`). All the changes will be described in related PR.

It's gonna be a breaking change and I guess it will influence this extension while you rely on the latest version of brainly style-guide.

Is there any way we can make this transition a bit easier for you? (i.e. we can postpone releasing it for a 1 day).

**Comment by seahindeniz** [comment]
@matzimowski can ask for a date so I can make changes?

**Comment by matzimowski** [comment]
https://github.com/brainly/style-guide/pull/1771 will be merged tomorrow in the morning i guess. Then I hope to have it on at brainly production the same day but couple of hours later.  I can ping you 1h before. wdyt?

**Comment by seahindeniz** [comment]
@matzimowski sgtm :+1:

**Comment by matzimowski** [comment]
@seahindeniz renamed buttons should appear on the page  in ~1h

**Comment by matzimowski** [comment]
@seahindeniz they are already on the page

**Comment by seahindeniz** [comment]
@matzimowski got it. I have deployed the new version on Chrome web store
