### ISSUE TITLE
Quick Action Button covering edit option elements in Indonesia Website

### ISSUE THREAD

**Issue by HerendraTJ** [seahindeniz/BrainlyTools_Extension#116]
**Describe the issue/bug [a clear and concise description of what the bug is.] :**
There should be edit button but it's covered by quick action buttons. I suggest you to able moving the quick action button based on the user desire. 

**To Reproduce [add steps to reproduce the behavior below] :**
Just turn on the tools and the edit button is covering the edit question button

**Screenshots [paste below]**
![image](https://user-images.githubusercontent.com/24410807/80626555-d0ae1680-8a78-11ea-8ed2-65f214e54882.png)

It should be
![image](https://user-images.githubusercontent.com/24410807/80626655-f76c4d00-8a78-11ea-8b4d-d332fbac6459.png)

**Comment by seahindeniz** [comment]
A rare case indeed. We usually dont use the edit link after asking question on daily basis. But I see your point I'll make changes accordingly

**Comment by seahindeniz** [comment]
I think having this kind of placement would solve the issue
![image](https://user-images.githubusercontent.com/5789670/80685547-0b8f6900-8ad0-11ea-8578-c395032b1ec9.png)
