### ISSUE TITLE
Reported contents confirmer

### ISSUE THREAD

**Issue by Surya150803** [seahindeniz/BrainlyTools_Extension#12]
Hi Sir , 

Some people report good answers of moderators for taking revenge against mods for deleting their answers. 

So, We would like to have a new feature, that will confirm all reported answers of that person at one click. 

And Don't worry about having this privilege for all, Only some trusted people will have it.

**Comment by seahindeniz** [comment]
I'm not my friend. It's acceptable and I can add some input in moderation panel to putting a victim users id and that function wil be going to search the entire reported contents and matches the id numbers of owner of the content and if it is the same, it'll confirm it quickly

**Comment by seahindeniz** [comment]
And also, I'll add a two checkboxes named as a **search in questions** and **search in answers** will be a choice for confirmer.

**Comment by Surya150803** [comment]
That's just awesome!

**Comment by BrainlHaezel** [comment]
I would rather suggest adding the reportee ID in search option instead of Victim and then confirm, Date wise answer reported in particular time frame. @seahindeniz @Surya150803

**Comment by Surya150803** [comment]
Didn't understood @BrainlHaezel :thinking:

**Comment by KalpeshPrabhakar** [comment]
Instead of doing all for a victim we can prevent reporting option for that profile @BrainlHaezel mam. Maybe like Time Ban facility for moderators. So When we block a person from reporting, naturally we dont confirm bad answers also by confirming it with more stability in panel. :)

**Comment by BrainlHaezel** [comment]
We can have this additionally. Because it won't solve our main problem, because the moment ban is gone, they will again start reporting, its the same like banning and as soon as the ban is over, they repeat or will create a false profile. 

We additionally need support from the extension in order to confirm the false reporting of the answers.

**Comment by Surya150803** [comment]
Yes, I agree with @BrainlHaezel

**Comment by seahindeniz** [comment]
I'm changing the request title and purpose to **Reported content confirmer** because there is no reasons to restrict this feature for only answers :p 

I'll add another condition for selecting the content type as Question or Answer
