### ISSUE TITLE
Corrected Filter BTools button Undefined

### ISSUE THREAD

**Issue by HerendraTJ** [seahindeniz/BrainlyTools_Extension#126]
**Describe the issue/bug [a clear and concise description of what the bug is.] :**
If you go to the waiting to be corrected , the btools show undefined

**To Reproduce [add steps to reproduce the behavior below] :**
1. Go To brainly.co.id/tasks/archive_mod
2. Select "Untuk Dikoreksi"
3. Drag to the desire task.
4. Undefined triggered.

**Screenshots [paste below]**
![image](https://user-images.githubusercontent.com/24410807/81478596-bcbc9e80-9248-11ea-98e6-618c8d8a527f.png)

YT Video to reproduce this issue:
https://youtu.be/3gjtMnqyPGc

**Comment by seahindeniz** [comment]
Thanks for reporting this, @HerendraTJ
