### ISSUE TITLE
Shortcuts in View User Content

### ISSUE THREAD

**Issue by antonio9990** [seahindeniz/BrainlyTools_Extension#131]
Ability to delete selective answers (like Delete solutions) & ban users directly from View User Content. In this way, we avoid using 2 tabs and we can give speed for moderators. Like this https://prnt.sc/sj33di

**Comment by seahindeniz** [comment]
Hello @antonio9990 

We already have this feature and it's restricted with privilege. You need to talk with your community manager to have that power. If it's ok, CM will give it to you

**Comment by seahindeniz** [comment]
I'm closing this because we already have it :fist_raised:
