### ISSUE TITLE
Toggle Option in User content Selective deletion

### ISSUE THREAD

**Issue by KaiDrolop** [seahindeniz/BrainlyTools_Extension#133]
Our toggle function is based on the status of select all checkbox state.

 So each time you switch, it changes all checked states of individual checkboxes to be the same as select all checked state.

 But my need is to have all individual checkboxes to be toggled to it's opposite of it's checked state.

As said in DM , don't remove the old logic but add this one 
![9186f048-9202-465c-8222-8817e8b0](https://user-images.githubusercontent.com/50515478/82886979-fe8b5b80-9f4f-11ea-9426-7180d641403d.gif)

**Comment by seahindeniz** [comment]
![7263429c-89b7-4386-96ac-ecc57f75cbb3](https://user-images.githubusercontent.com/5789670/94307918-5aa5d100-ff7e-11ea-8ed5-6d78883f332b.gif)

**Comment by KaiDrolop** [comment]
Awesome.This should be useful.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
