### ISSUE TITLE
"Kullanıcı İçeriğini Gör" Kısmında Hatalı Olarak Bildirilen Yanıtları Görüntüleme

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#134]
"Kullanıcı İçeriğini  Gör" kısmından doğrulama yaparken hata yapmamak adına, düzenlenmesi için işaretlenen yanıtların sol tarafında kullanıcı tarafından bildirildiğinde olduğu gibi bir ikon belirebilir. Bu sayede düzenlenmesi gereken içerikleri doğrulamamış oluruz.

**Comment by seahindeniz** [comment]
Özelliği eklemek için denemeler yaptım fakat Brainly, düzenlenmesi için bildirilmiş olup olmadığı bilgisini direkt olarak vermiyor. Dolaylı yol kullanarak çözüm sağlanabilir fakat bu da ekstra bağlantı açmaktan geçiyor. Bu yüzden isteğini oluşturamıyorum @NisiDominus 
Issue'yu kapatıyorum
