### ISSUE TITLE
Kullanıcı içeriğinde ek rengi aynı. 

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#138]
![Screenshot_20200623_012255](https://user-images.githubusercontent.com/62960189/85343308-322cb780-b4f5-11ea-86f1-657b94359834.jpg)

**Comment by seahindeniz** [comment]
@UgurhanKazanci61 profil idsini veya linkini paylaşabilir misin?

**Comment by seahindeniz** [comment]
![example](https://user-images.githubusercontent.com/5789670/86508804-969c2080-bdeb-11ea-9255-8c93fba0e2b5.gif)

Seçtiğin tema rengi siyah olduğu için sanırım bu sorunu yaşıyorsun. Eklenti, tüm mavi renkli ikonları değiştirecek şekilde ayarlı olduğu için seçtiğin tema rengine göre kendini uyarlıyor.
