### ISSUE TITLE
Visual Change to Pages in Mod Panel

### ISSUE THREAD

**Issue by HarshSaini800** [seahindeniz/BrainlyTools_Extension#139]
![Screenshot (218)](https://user-images.githubusercontent.com/67321824/85400639-5da3b680-b576-11ea-943b-6318ac0f955f.png)
Pages instead of being displayed all at once can be divided into sets which can be scrolled through left or right buttons.

**Comment by seahindeniz** [comment]
Hey @HarshSaini800 
Thanks for the suggestion. Here is an example of what we can now
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5789670/87072092-e7fd4300-c223-11ea-893e-0c66f656067f.gif)

Let me know if you don't like it

**Comment by HarshSaini800** [comment]
This looks really neat and great.. Can't wait for the update to roll out.. !
