### ISSUE TITLE
Missing Quick Delete Options on Question Pages for Answers

### ISSUE THREAD

**Issue by joy123333** [seahindeniz/BrainlyTools_Extension#146]
**Describe the issue/bug [a clear and concise description of what the bug is.] :**
Quick delete options are missing on the question pages for answers, but are still there for the question

**Screenshots [paste below]**
![image](https://user-images.githubusercontent.com/68306215/87485620-31c0a180-c607-11ea-8147-3e787a49c4f6.png)

**Comment by seahindeniz** [comment]
@joy123333 could you attach your profile link here, please?

**Comment by joy123333** [comment]
@seahindeniz here: https://brainly.com/profile/joy123333-154530
Thanks!

**Comment by seahindeniz** [comment]
@joy123333 I have just checked and seems like there is no issue with the quick delete buttons it works with no trouble. Could you please try to reinstall the extension?

**Comment by joy123333** [comment]
@seahindeniz I reinstalled the extension and the buttons are still missing.
This user is also missing them:
https://brainly.com/profile/Mistystar4881-9317391

**Comment by seahindeniz** [comment]
Thanks, @joy123333 I have found the bug and deployed the fix. Please wait a while for the new version to have published
