### ISSUE TITLE
Kullanıcı içeriğinde sayfalar arası hızlı geçiş

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#149]
![unknown](https://user-images.githubusercontent.com/62960189/87665140-1e304a80-c76f-11ea-85c7-189f536142d8.png)

**Comment by seahindeniz** [comment]
Seems like this is what you need
 
![image](https://user-images.githubusercontent.com/5789670/87672749-1034f680-c77c-11ea-870a-2e170322e79d.png)
