### ISSUE TITLE
Bio Section of Brainly's Profile Not visible

### ISSUE THREAD

**Issue by Surya150803** [seahindeniz/BrainlyTools_Extension#15]
Sir, The bio section which was designed to show the bio of users of app in website, and we can change it.

It ain't showing now, at first, After refreshing page several times, it used to appear. Now even after refreshing, It ain't appearing now.

Kindly see it to the earliest :)

Thanks!

Regards.

![capture](https://user-images.githubusercontent.com/47341818/52473130-10aa8480-2bbb-11e9-8da0-e1867548fc94.PNG)

**Comment by seahindeniz** [comment]
Could you please add the logs from the Console?

**Comment by Surya150803** [comment]
You mean this? 
![capture](https://user-images.githubusercontent.com/47341818/52473661-63d10700-2bbc-11e9-9429-a7e0dcbe1a51.PNG)

**Comment by Surya150803** [comment]
This was bottom of Console

**Comment by Surya150803** [comment]
Here's an ss of top of it.
![capture](https://user-images.githubusercontent.com/47341818/52473747-8d8a2e00-2bbc-11e9-8971-a9806db33b56.PNG)

**Comment by seahindeniz** [comment]
Yup, I need these logs but seems everything OK on logs. That will be going to hard to find the error :worried:

**Comment by Surya150803** [comment]
It's actually, Happening with everyone, Not just me
