### ISSUE TITLE
Toplu Puan Değiştirici Çoklu Puan Belirleme 

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#155]
Toplu Puan Değişimi menüsünde tüm puan inputlarının değiştirilmesini sağlayan bir özellik ekleyebilir miyiz? Talebimle ilgili örnek bir ekran alıntısı ve video ekledim 😊

![image](https://user-images.githubusercontent.com/47514611/88337752-e6616e00-cd3f-11ea-927e-69f4383e7ced.png)

Video : https://youtu.be/OWznwByxOcU

**Comment by seahindeniz** [comment]
Thanks, @NisiDominus for the perfect suggestion.

This will be introduced in the version 7.3.0 

![cd59c5ca-4f91-4217-a7a7-4176cafa0b46](https://user-images.githubusercontent.com/5789670/92998124-b99c2c80-f520-11ea-9cf6-ab7bd7eb6b2f.gif)
