### ISSUE TITLE
Answers with HTML codes and tags don't appear when the green button is clicked.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#156]
**Is your feature request related to a problem? Please describe.**
Yes, answers/questions containing **HTML tags** usually don't appear when the green button is clicked.

Link to the question mentioned in the video --> https://brainly.in/question/19915507

**Describe the solution/idea you'd like**
A way to view answers/questions with HTML tags/codes in the new mod panel.

In case it isn't possible, it'll be nice to have an automated system that prevents users from including HTML tags in their answers.

![screencast-brainly in-2020 07 24-16_18_24 (1)](https://user-images.githubusercontent.com/68370357/88384573-4dc40000-cdca-11ea-9bd0-3342ffe14c79.gif)

**Comment by seahindeniz** [comment]
This is related to Brainly's moderate all.
Brainly Tools will no longer have any new features or support the old moderate all for the sake of maintaining the new reported contents page. 
I'm closing this issue
