### ISSUE TITLE
An option to un-approve approved answers in the mod panel.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#158]
**Is your feature request related to a problem? Please describe.**
Yeah, but not related to the extension since an "un-approve" option doesn't show up (with or without the extension) in the mod panel for an approved answer.

**Describe the solution/idea you'd like**
1. A quick delete button that'll enable un-approving approved answers.
2. A checkmark beside approved answers in the mod panel.

**Describe expected outcome from your solution**
1. A way to unapproved approved answers through the panel.
2. A way to identify approved answers without having to check the log.

Video file: Approval bug.
Image: Suggestion of a display of an approved answer in the mod panel. 

![approvalbug](https://user-images.githubusercontent.com/68370357/88472747-d3af8a80-cf33-11ea-82ed-54bf40ceb958.gif)
![Screenshot_2](https://user-images.githubusercontent.com/68370357/88472751-e6c25a80-cf33-11ea-8624-c07b351a5cf6.png)

**Comment by seahindeniz** [comment]
Hi

The extension will no longer have more features on the moderate all than current features. So this feature will be available on the new reported contents page

**Comment by Tomboyish44** [comment]
Hey, 

Awesome, got it. ✔

Thank you!
