### ISSUE TITLE
Kullanıcıyı Yeni Sekmede Açma

### ISSUE THREAD

**Issue by alliay479** [seahindeniz/BrainlyTools_Extension#160]
Ödev sayfasında, ödevi ekleyen hesap hiçbir şekilde yeni sekmede açılamıyor. Sadece tıklayarak mevcut sayfada açılabiliyor. Klavye kısayolları veya sağ tık menüsü ile profil yeni sekmede açılabilir olmalı

**Comment by seahindeniz** [comment]
Hey @alliay479, can you confirm that the feature request in #377 covers the need in your feature request?

**Comment by alliay479** [comment]
Yes it meets my need
