### ISSUE TITLE
Quick delete buttons

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#164]
**Describe the issue/bug**
The quick delete buttons for the questions has vanished since the last (brainly) interface update
**Screenshots**
![image](https://user-images.githubusercontent.com/39934266/89595300-2b969d00-d822-11ea-9377-4a2fe7cb7c72.png)

**Comment by joy123333** [comment]
Mine are also missing again (after disappearing then returning after an update).
I tried redownloading the extension.
My profile link: https://brainly.com/profile/joy123333-154530
Thanks!

**Comment by bsoyka** [comment]
@seahindeniz While the buttons are now showing up for me, it seems like the buttons for answers are using the reasons set for questions.

**Comment by seahindeniz** [comment]
It will be fixed on the next version release @bsoyka
