### ISSUE TITLE
Incorrect reason for deletion

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#173]
**Describe the issue/bug :**

There is a problem with the deletion pattern. It is written "SPAM" whereas in this case it should be written: "Lien du contenu plagié : .....
Humm malheureusement ta réponse est la copie d'une autre source. Nous sommes sûrs que tu es suffisamment intelligent pour trouver une réponse par toi-même ;) 
De plus, sache que copier (une réponse ou le contenu d'une autre page internet) est une violation des droits d'auteurs ce qui est illégal. Ce type de comportement peut entraîner un avertissement et après récidive, un bannissement du site.".

**To Reproduce :**

1. Go to the new page "Reported contents"
2. Moderate an answer

**Screenshots [paste below, optional]:**

![Screen](https://user-images.githubusercontent.com/64775524/91658525-23e8b200-eac9-11ea-98e9-cfb0de464739.jpeg)

**Comment by tom-rh** [comment]
Maybe a link with this problem :

![image](https://user-images.githubusercontent.com/64775524/91661613-6caa6600-eadd-11ea-8ffd-ad96197610df.png)

**Comment by seahindeniz** [comment]
The issue occurred with Qdbs in the question page

![image](https://user-images.githubusercontent.com/5789670/91890025-7bd51380-ec97-11ea-8f56-3da008aae84a.png)
