### ISSUE TITLE
Automatic deletion of questions of bots

### ISSUE THREAD

**Issue by Surya150803** [seahindeniz/BrainlyTools_Extension#18]
Sir, I already had a talk with you in Dm, So Probably, You already know what this issue is related to. 

Some of the key words are : 

- Vashikaran
- Love Specialist
- love m-a-r-r-i-a-g-e s-p-e-c-i-a-l-i-s-t
- Black Magic
- bAbAji
- Love Spells
- http://www.orignalsupplements.com
- https://simplyevents.io/
-  Love marriage problem solutions 
- Husband wife problem solutions
- Get your lost Love back by astrology
- Keto

Thanks Sir :beers:

**Comment by seahindeniz** [comment]
This feature is also requested by Magda from brainly.lat

Their pattern is "find questions contains (whatsapp or telephone) and numbers start with (9 or 6) and must be 9 digits"

**Comment by seahindeniz** [comment]
..and also it'll be available for the brainly.lat
