### ISSUE TITLE
Quick delete reasons on buttons are not saved.

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#181]
**Describe the issue/bug :**

When refreshing the page, the configured deletion reasonss are not saved.

**To Reproduce :**

1. Change a deletion reason.
2. Refresh.

**Screenshots [paste below, optional]:**

![Issue1](https://user-images.githubusercontent.com/64775524/91662031-1b4fa600-eae0-11ea-94c6-6cb5ed1c558a.gif)

**Profile link [paste below] :**

https://nosdevoirs.fr/profil/its1tom-578978

**Comment by seahindeniz** [comment]
Fixed in https://github.com/seahindeniz/BrainlyTools_Extension/commit/4532d1448184df662786b79b47ebe693a3a55717
