### ISSUE TITLE
A way to directly close the ticket when viewing the log at the very bottom of a ticket.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#184]
**Is your feature request related to a problem? Please describe.**
Nope. But it's hard to close the ticket, view the link and content of the question & view the time left to moderate the content when we're at the bottom of the ticket.

**Describe the solution/idea you'd like**
1. A way to close the ticket without having to scroll all the way up.
2. Or a shortcut key that closes the ticket.
3. A button to jump to the top of the report.

**Describe expected outcome from your solution**
To be able to close tickets, or view the link and content of a question instead of having to scroll to the top.

Profile link [paste below] -->
https://brainly.in/profile/Tomboyish44-2709968

**Comment by seahindeniz** [comment]
I will reopen this for adding a button for jumping to the top of the moderate panel
