### ISSUE TITLE
yorumlar

### ISSUE THREAD

**Issue by grknzsy** [seahindeniz/BrainlyTools_Extension#2]
td kısmındaki yorumlar sekmesine geçtiğimde yorumları toplu olarak silebileceğim bir özellik ekleyebilirsen iyi olur @seahindeniz. her eklenti kullanıcısının bu özelliği kullanması gerekmez. teşkür. :)

**Comment by seahindeniz** [comment]
Yorumlar silinirken, kullanıcıya uyarı verilmesi gerekir mi? Ya da uyarı ver/verme şeklinde bir onay kutusu eklesem iyi olur mu?

**Comment by grknzsy** [comment]
uyarıya gerek yok şahin :) sadece ben kullanacağım zaten. amaç o çoğu gereksiz ve anlamsızca şikayet edilmiş içeriği silip td'yi rahatlatmak.

**Comment by seahindeniz** [comment]
Abi sadece sen kullanacaksın ama eodev de :smile: Diğer marketleri de düşün, oranın da adminleri var ve eklediğim zaman, eklenti adminleri olunca onlarda da gözükecek. O yüzden sordum ama yine de seçenek eklemeyi düşünüyorum. Eklenmesi istenirse işaretlenir gibisinden

**Comment by seahindeniz** [comment]
Added [9d8bdec](https://github.com/seahindeniz/BrainlyTools_Extension/commit/9d8bdec308cffc70d307bb41ba580563dffbcefc)
