### ISSUE TITLE
Quick Delete Buttons don't appear when question links are visited by using the CTRL + left click shortcut, or when in the background. (sometimes)

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#201]
**Describe the issue/bug :**
Quick Delete Buttons don't appear when question links are visited by using the CTRL + left click shortcut, or when in the background **_sometimes._**

**To Reproduce :**
(might not work always)
1. Visit the [homepage](https://brainly.in/). 
2. Open a question in a new tab, but don't visit it. 
3. After a couple of minutes/seconds, visit the tab, the QDBs' _might not_ be there.

Profile link [paste below] -->
https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
To future me:
Use mutation observer as solution

**Comment by seahindeniz** [comment]
Seems like the problem isn't solved
