### ISSUE TITLE
Urgency of a way to stop exclusion of 'verified questions' using quick buttons

### ISSUE THREAD

**Issue by juanbomfim22** [seahindeniz/BrainlyTools_Extension#203]
**Is your feature request related to a problem? Please describe.**

Recently, this problem have been making moderators and excelent answerers uncomfortable as their correct and verified answers have been deleted directly because of the usage of quick delete question button in tasks/archive_mod section. 

**Describe the solution/idea you'd like**

It's urgent to update or add, in tasks/archive_mod, some of these features in reported questions:

* Alert if a specific reported question has verified answers or moderators' when one is deleting a question.
* Display the username of actual question answerers in order to know if some Brainly member has answered the question.

**Describe expected outcome from your solution**

Verified answers can't be reported. However, their questions still can. This feature will work in order to reduce the number of troll reported questions deleted so that it can maintain the proper content and the moderator who intends to delete it should become aware of this irreversible exclusion. 

Example: 

![2](https://user-images.githubusercontent.com/55420785/92410337-2f1b8d80-f11a-11ea-9755-dbac34d3f967.jpeg)
![0](https://user-images.githubusercontent.com/55420785/92410328-2a56d980-f11a-11ea-98ea-1adf7e47c8c6.jpg)
![1](https://user-images.githubusercontent.com/55420785/92410333-2c209d00-f11a-11ea-83d9-0bf7cbf7cdcd.jpeg)
![4](https://user-images.githubusercontent.com/55420785/92410844-dc42d580-f11b-11ea-84d2-5f0a2c98a745.jpeg)

**Comment by seahindeniz** [comment]
Thanks.I'm kind of busy for next couple days. When I get free, I'll se what I can do. 

Also;
Extension will not going to have new features for Brainly's moderate all page. Instead, extension has a new page called "reported contents" which is a way more enhanced replacement compared to moderate all and its in beta stage now. Further feature requests related to moderate all, will be implemented to new page if possible :v:

**Comment by juanbomfim22** [comment]
@seahindeniz Hi. Thank you so much for your effort in this extension, I and most moderators appreciate it. If you need anything from me, just tell me and I'll do my best do accomplish it.

**Comment by seahindeniz** [comment]
The solution I come up with is simply **not** allowing the ability to use the quick delete buttons on questions that have verified answers.
This will safely redirect moderators to moderate from the moderate panel or the question page. Answers will be safe in this way.

![image](https://user-images.githubusercontent.com/5789670/92989802-99984900-f4df-11ea-98e2-4eb4cc2ff445.png)

ps: popup will contain a list of verified answer details. Each of the verify action will be shown

![image](https://user-images.githubusercontent.com/5789670/92989844-03185780-f4e0-11ea-87f4-183e5e2a45b3.png)

**Comment by seahindeniz** [comment]
The "why" I don't go to the "confirm" approach is, a moderator can click the **OK** button by accident and this will still lead them to unsafety.

![image](https://user-images.githubusercontent.com/5789670/92989999-14159880-f4e1-11ea-9ba9-4192617bc4fd.png)

**Comment by seahindeniz** [comment]
The same decision applies to the quick delete buttons on the question content in the question page as well

![image](https://user-images.githubusercontent.com/5789670/92990193-fba67d80-f4e2-11ea-81df-2f0d2893a3fe.png)

**Comment by seahindeniz** [comment]
For the moderate all page; as I mentioned before, we have a new reported contents page that will be a replacement for it.
My plan is to share it with all extension users who have moderation powers so that they will get access to the reported contents page. This also leads me to mark all of the features for the moderate all page as deprecated and remove them for some time later in order to maintain safety and development related issues.

**Comment by juanbomfim22** [comment]
> The solution I come up with is simply **not** allowing the ability to use the quick delete buttons on questions that have verified answers.
> This will safely redirect moderators to moderate from the moderate panel or the question page. Answers will be safe in this way.
> 
> ![image](https://user-images.githubusercontent.com/5789670/92989802-99984900-f4df-11ea-98e2-4eb4cc2ff445.png)
> 
> ps: popup will contain a list of verified answer details. Each of the verify action will be shown
> 
> ![image](https://user-images.githubusercontent.com/5789670/92989844-03185780-f4e0-11ea-87f4-183e5e2a45b3.png)

Hi again! Could you please tell me if this new reported page is available already? I've noticed for example some changes in quick delete buttons on the question content, yayy!! But nothing about this content page on Brainly BR. Bear with me, but what you meant exactly: you were still working on it and it's gonna be added soon OR it's already been added since this issue was closed?

**Comment by seahindeniz** [comment]
Hi @juanbomfim22 

Its called, "Reported contents" page and yes, this page is alive and it's in beta stage for the time being. You can ask permission from your extension manager to get access or you can wait until it is open to every extension user who have moderation powers
