### ISSUE TITLE
Yeni TD kısmında A ve D tuşu ile içeriği geçme

### ISSUE THREAD

**Issue by HAPPYxXxATOM** [seahindeniz/BrainlyTools_Extension#206]
**Describe the issue/bug :**
Yeni td kısmında A ve D tuşları ile ileri geri gidilmiyor.

**To Reproduce :**
1. 
2. 
3. 

**Screenshots [paste below, optional]:**

**Comment by seahindeniz** [comment]
Duplicate of #205
