### ISSUE TITLE
Ek bilgiler alanına göre şikayetleri filtreleme

### ISSUE THREAD

**Issue by HAPPYxXxATOM** [seahindeniz/BrainlyTools_Extension#208]
Td deki içerikleri Ek bilgilere göre filtreleme
![unknown-3](https://user-images.githubusercontent.com/69786557/92808452-6f9e3400-f3c4-11ea-8c57-21ea639d1fd5.png)

**Comment by seahindeniz** [comment]
![image](https://user-images.githubusercontent.com/5789670/93688614-b3cdba80-facf-11ea-8af8-3cd0ae9583b3.png)
