### ISSUE TITLE
Ability to see special ranks in the question page

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#225]
Sometimes we have to delete some answers to get them optimized. But, after Brainly's new UI update, the special ranks are not visible on the question page. For this reason, the answers of the moderators can be deleted by mistake. To correct this mistake, a feature can be added to the extension that shows special ranks on the question page.

![image](https://user-images.githubusercontent.com/47514611/93617716-011e2f00-f9df-11ea-90f9-610e6ca455d2.png)

**Comment by seahindeniz** [comment]
Alright, I think this change should be enough to help you guys out!

![image](https://user-images.githubusercontent.com/5789670/93661545-47b46d80-fa61-11ea-898a-1b1f8f0524f9.png)
