### ISSUE TITLE
A 'Jump to Log' button beside questions.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#232]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution/idea you'd like**
A view to view the log of questions instead of scrolling to the bottom of the page.

A suggestion of how it could look attached below. ⬇

![image](https://user-images.githubusercontent.com/68370357/93707428-1e244080-fb4c-11ea-9a7e-dd2382ce6bdb.png)

**Describe expected outcome from your solution**
A button (or anything else) that enables viewing the log in just one click without having to scroll. 

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
All extension users are not moderators so the "jump to log" button will be changed as the "jump to bottom" button like this 
![image](https://user-images.githubusercontent.com/5789670/93707528-35593300-fb38-11ea-9089-a5aa67920dc3.png)

To future me:
The button can be fixed to a corner of the page and the visibility state can be managed with an intersection observer
