### ISSUE TITLE
Extension Connection Error

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#235]
The extension started to crash frequently after the version 7.3.0 update. Therefore, it does not work stably.
![image](https://user-images.githubusercontent.com/47514611/93716545-13cc6b80-fb79-11ea-9665-89fee53bdeda.png)

**Comment by seahindeniz** [comment]
To reproduce, send thanks to someone from a profile page on eodev.com

Unicode strings are the problem here
