### ISSUE TITLE
Use the new moderate panel in the question page

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#242]
Brainly's built-in moderation panel can be replaced with the extension's new moderation panel.

From:
![image](https://user-images.githubusercontent.com/47514611/94258202-2a861000-ff35-11ea-8e5d-0c00d2d34557.png)

To:
![image](https://user-images.githubusercontent.com/47514611/94258152-16421300-ff35-11ea-97a3-a6db35c11af5.png)

**Comment by seahindeniz** [comment]
Here is how will it look:

![e91f8d11-f6e4-4dba-b20e-ef6856113078](https://user-images.githubusercontent.com/5789670/95025444-7bfb7100-0692-11eb-9866-4a98e4d91476.gif)

Some users may not like this change so they will still be able to moderate from the old moderate panel. They just need to hold CTRL or SHIFT key from their keyboard while clicking the Moderate button or they can long-click on the moderate panel too ✌️
