### ISSUE TITLE
An error is displayed while the process is running correctly.

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#243]
**Describe the issue/bug:**

An error is displayed while the process is running correctly.
On the GIF, the extension displays an error whereas after refreshing the page, I deleted the question.

**To Reproduce:**

1. Choose a question
2. Use the quick delete buttons

**Screenshots [paste below, optional]:**

![Issue5](https://user-images.githubusercontent.com/64775524/94339113-b8c2ca80-fff7-11ea-8a9c-8d6e86e76527.gif)

**Profile link [paste below]:**

https://nosdevoirs.fr/profil/its1tom-578978

**Comment by tom-rh** [comment]
I don't know if it's useful for the resolution but here's a screenshot of the console.

![image](https://user-images.githubusercontent.com/64775524/94339945-3ab5f200-fffe-11ea-99b7-fd2ac8a99297.png)

**Comment by seahindeniz** [comment]
Thanks @tom-rh it's pointing the exact reason
