### ISSUE TITLE
Moderatörler için uygulama yüklemeden cevapları görme

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#246]
![Screenshot_20200926_185259_com yandex browser](https://user-images.githubusercontent.com/62960189/94345611-ce53e680-002f-11eb-86a8-57b025fa6320.jpg)

**Comment by seahindeniz** [comment]
I have tried to find a solution for this but it's related to Brainly and a potential solution isn't going to be a reliable one due to frequent changes in the layout of the question page.
