### ISSUE TITLE
Extension Can't Fetch Details of Moderators in Mass-Message Sender

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#255]
![error](https://user-images.githubusercontent.com/47514611/94600664-e54a4100-029a-11eb-95d0-6e09b471691b.gif)

**Comment by seahindeniz** [comment]
Have you tried refreshing the page after that error?

**Comment by NisiDominus** [comment]
> Have you tried refreshing the page after that error?

Yes, I tried it over and over.

**Comment by NisiDominus** [comment]
* also tried on a different device

**Comment by seahindeniz** [comment]
Well, I can confirm this issue is related to Brainly. As seen in the GIF that you've recorded, error logs are indicating to rejected connections with 403. There is not much I can do about this but I'll try to find a solution anyway

**Comment by NisiDominus** [comment]
Thank you 😊❤
