### ISSUE TITLE
A way to see user warnings from profile page without visiting warnings page

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#257]
Sağ tarafta uyarı içeriklerini görürsek hızlı işlem yapmamız açısından yararlı olacaktır.

![IMG_20201001_190623](https://user-images.githubusercontent.com/62960189/94834650-4b5cd280-0419-11eb-8123-a7f00f6c5bca.png)

**Comment by seahindeniz** [comment]
Here is how will it looks like

![e418268e-3b16-469c-9279-fbd62ab5a8ee](https://user-images.githubusercontent.com/5789670/94920785-a21ce780-04bf-11eb-9280-72eced8e55c1.gif)
