### ISSUE TITLE
An option to filter reports by content using the filter reports feature.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#271]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution/idea you'd like**
It'll be nice to have an option to filter reports by the content present in them. There are a lot of questions/answers having the words "zoom", "I don't know" etc, and if we can filter them out easily, we can moderate & remove them quickly. 

**Describe expected outcome from your solution**
An option that enables filtering reports by the content present in them.

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
![eb0094b9-684e-4d62-9837-d54bdcb1457f](https://user-images.githubusercontent.com/5789670/97219730-713c8380-17db-11eb-82cd-2fe94e240c31.gif)

Here is the solution

**Comment by Tomboyish44** [comment]
Thank you! 😄
