### ISSUE TITLE
A new colour for tasks that have already been deleted.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#275]
**Is your feature request related to a problem? Please describe.**
Yeah, report boxes get coloured dark blue while moderating when the question/answer has already been deleted or when there's a connection error and there isn't a direct way to discern both of them.

![image](https://user-images.githubusercontent.com/68370357/95719045-ea40c480-0c8c-11eb-9828-527294e0a18c.png)

**Describe the solution/idea you'd like**
It'll be nice to have a new colour for report boxes when the question/answer has already been deleted, so that it's easier to tell when a question/answer has already been deleted.

**Describe expected outcome from your solution**
A new colour for reported content boxes that helps signify that a content has been deleted.

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
The purple color will be used on reports that have already moderated

![image](https://user-images.githubusercontent.com/5789670/95742916-807ae780-0c99-11eb-9057-76b719570285.png)
