### ISSUE TITLE
A separate panel to filter reported contents that have been asked/answered by users who hold special ranks.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#277]
**Is your feature request related to a problem? Please describe.**
Kind of, but not really. Some users report many valid answers of moderators, stars, or users who hold similar special ranks unnecessarily and at times they get deleted by other moderators, leading to incorrect moderations. 

**Describe the solution/idea you'd like**
A panel that displays all the reported answers & questions that contain content posted by users holding special ranks [Brainly Stars, Moderator, Best User, etc] so we can moderate them quickly.

And maybe ways to filter them by specific ranks, profile link/ID/Username, popularity of answers & other useful filters.

**Describe expected outcome from your solution**
A way to easily view reported content that has been posted by special rank holders.

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
![Screenshot_37](https://user-images.githubusercontent.com/5789670/97194352-1abf4d00-17bb-11eb-956a-0e24c7b5d222.png)

Here is the preview of the solution

**Comment by Tomboyish44** [comment]
Awesome, thank you! ✨
