### ISSUE TITLE
Solicitar uma segunda correção

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#280]
**Is your feature request related to a problem? Please describe.**
Não.

**Describe the solution/idea you'd like**
Ao enviar uma resposta para correção não é possível enviá-la novamente. Sendo necessário aprovar e depois enviar para correção. 

**Describe expected outcome from your solution**
Um botão para solicitar a correção novamente, sem necessitar aprovar e pedir correção em seguida. 
![Captura de Tela 2020-10-12 às 14 40 41](https://user-images.githubusercontent.com/39934266/95780045-33971100-0c99-11eb-961b-30a6d54b66ae.png)
![test](https://user-images.githubusercontent.com/39934266/95781164-427ec300-0c9b-11eb-8e2c-9a7b458d2728.gif)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by seahindeniz** [comment]
Hi @Maxonvs 
Thanks for reporting it!

Here is the solution that will be deployed on the next version release:
![3427b68d-cafd-4977-a883-193f1b115ba5](https://user-images.githubusercontent.com/5789670/95861260-dc14a600-0d69-11eb-96ec-98f3364e4f40.gif)
