### ISSUE TITLE
Erro ao aplicar pontos

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#281]
**Describe the issue/bug:**
Não é possível aplicar ou retirar pontos de um ou mais usuários. Apesar da mensagem de sucesso, os pontos não são alterados.

**To Reproduce:**
1. Acesse o menu mass-manage users
2. Preencha a ids dos usuários
3. Confirme a alteração nos pontos

**Screenshots [paste below, optional]:**
![Captura de Tela 2020-10-12 às 16 35 00](https://user-images.githubusercontent.com/39934266/95788645-eb341f00-0ca9-11eb-8b4c-32211781aa41.png)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by seahindeniz** [comment]
I'm closing the issue since the "Change points" section has removed

**Comment by Maxonvs** [comment]
> Hey @Maxonvs
> 
> Change Points tab will be removed on the next version release for the sake of Mass-Point changer. Please try to use that tool instead

Oh, okay. If I understood correctly: the "mass-point" and "change-rank" tools are tools that are still in development, right?
