### ISSUE TITLE
Change ranks

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#282]
**Describe the issue/bug:**
A opção para mudar ou acrescentar ranks especiais ao usuário não aparece.

**To Reproduce:**
1. Acesse o menu mass-manage users
2. Preencha o id dos usuários

**Screenshots [paste below, optional]:**
![Captura de Tela 2020-10-12 às 16 50 39](https://user-images.githubusercontent.com/39934266/95789228-22570000-0cab-11eb-8a12-288c319e4f0d.png)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by seahindeniz** [comment]
duplicate of #55
