### ISSUE TITLE
Toplayer não fecha automaticamente

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#284]
**Describe the issue/bug:**
Após deletar uma tarefa no novo toplayer, ele não fecha automaticamente e mostra uma mensagem de erro.

**To Reproduce:**
1. Acesse uma tarefa qualquer pelo novo toplayer
2. Apague a tarefa

**Screenshots [paste below, optional]:**
![image](https://user-images.githubusercontent.com/39934266/95791547-9b585680-0caf-11eb-801d-c05a62f42776.png)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by Maxonvs** [comment]
> Hey @Maxonvs
> 
> Can you tell me from which page you were deleting the question?

Perdão 😅  Foi dentro da página da questão:
https://brainly.com.br/tarefa/33791559

**Comment by seahindeniz** [comment]
No problem 😉
