### ISSUE TITLE
Ability to mass-moderate contents that are visible.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#289]
**Is your feature request related to a problem? Please describe.**
_Not really._ But, while mass-moderating, say I've got 1000 reports that have been filtered, before deleting them, I gotta check to make sure all 1000 are invalid, then delete all the filtered reports.

It'll be a bit more efficient to do it in chunks with an option that enables deleting content that's _displayed_ only.

**Describe the solution/idea you'd like**
A feature that enables mass-moderating contents that get **displayed** on the reported contents page, similar to how it's possible to delete filtered contents using the mass-moderate tool. 

**Suggestions:**

- A button to choose Visible reports to moderate. 

![image](https://user-images.githubusercontent.com/68370357/96087933-48b2b080-0ee2-11eb-9392-df3b6c5b87ce.png)

If #140 is added as a feature;

- Select boxes beside reported content boxes. 

- An option that selects all report boxes that are currently visible on the page. ["Select visible reports"]

- Or any other cool feature to moderate visible reports.

**Describe expected outcome from your solution**

Ability to mass-moderate contents that are visible in the reported contents page. 

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
The solution I can come up with having it like this

![0230f7a4-137b-46b3-9a6a-f14805103e1c](https://user-images.githubusercontent.com/5789670/96498598-eeed1600-1254-11eb-926d-dc968014e2eb.gif)

**Comment by Tomboyish44** [comment]
Awesome! Thank you! 😄

**Comment by seahindeniz** [comment]
And this new little button is for marking a report as ignored

![a8363015-e120-4b50-8a21-64ad456b8e87](https://user-images.githubusercontent.com/5789670/96562707-bc313500-12c9-11eb-9eab-c7989f1308ce.gif)

**Comment by seahindeniz** [comment]
And the last button is for marking visible reports as ignored to avoid clicking the ignore button on each report boxes

![8d7bdba4-f521-48ba-97ba-e657f60e7946](https://user-images.githubusercontent.com/5789670/96579273-40da7e00-12df-11eb-8fb7-6439faa7b440.gif)
