### ISSUE TITLE
Mass point changer editing 

### ISSUE THREAD

**Issue by Happiestwriter012** [seahindeniz/BrainlyTools_Extension#29]
@seahindeniz Can you make changes to the mass point editor like
I want it to take the number of points along with links automatically.
Like,
Brainly.in/sahin-345684 [ + 5000] should add it directlyAlso please make a single confirming option than that many

**Comment by seahindeniz** [comment]
![image](https://user-images.githubusercontent.com/5789670/53998064-8d476900-414f-11e9-8598-7be5009f37cc.png)

I've changed the Mass-Point changer a bit but I'll looking to that link proposal later

**Comment by Happiestwriter012** [comment]
Okay :)

**Comment by Happiestwriter012** [comment]
So the feature of pointer taking the points input directly isn't added yet
