### ISSUE TITLE
Some title changes for a few icons.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#293]
**Is your feature request related to a problem? Please describe.**
Not really, but some icons can be replaced with others or can be given titles so it's easier to understand their functions on the reported contents page

**Describe the solution/idea you'd like**

Some suggestions for making icons in the reported contents page similar to the old moderate panel as discussed through DM;

- [x] The ✏ icon used to moderate reports could be replaced with the shield icon

- [x] The correction flag that's used to report for correction could be replaced with a pencil icon

- [x] The ". . ." icon that's used to view more delete options could be replaced with a trash icon

- [x] The blue & green flags can be titled as "Not Corrected and "Corrected"

- [x] The name of the default view for QDB's that's being used can be written beside "Default" in brackets (or vice-versa)

- [x] The "+" icon for extending time can be titled with "Extend by 15 minutes" or anything similar

- [x] "Load All Reports" can be replaced with "Fetch All Reports" so that it's relatable with the "visible", "filtered" & "fetched" counters

- [x] Similarly, in the "Filters can be applied only to those reports that have been "**loaded**" line, "loaded" could be replaced with **"fetched"**

**Describe expected outcome from your solution**
Ease in knowing what function icons perform

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
> The ✏ icon used to moderate reports could be replaced with the shield icon

![image](https://user-images.githubusercontent.com/5789670/96873502-b11f0600-147d-11eb-86c9-0dcd341c00b7.png)

**Comment by seahindeniz** [comment]
> The correction flag that's used to report for correction could be replaced with a pencil icon

![Screenshot_31](https://user-images.githubusercontent.com/5789670/96873666-ea577600-147d-11eb-8ea6-e3a08a2b8a84.png)

**Comment by seahindeniz** [comment]
> The blue & green flags can be titled as "Not Corrected and "Corrected"

![image](https://user-images.githubusercontent.com/5789670/96873842-1f63c880-147e-11eb-9c80-68eb4b93743d.png)

![image](https://user-images.githubusercontent.com/5789670/96873784-0e1abc00-147e-11eb-8c65-1737aee1341f.png)

**Comment by seahindeniz** [comment]
> The name of the default view for QDB's that's being used can be written beside "Default" in brackets (or vice-versa)

![image](https://user-images.githubusercontent.com/5789670/96873965-43270e80-147e-11eb-874f-48d33c0373ff.png)

**Comment by seahindeniz** [comment]
> The "+" icon for extending time can be titled with "Extend by 15 minutes" or anything similar

![image](https://user-images.githubusercontent.com/5789670/96874106-6c479f00-147e-11eb-91b9-5d19047c37aa.png)

**Comment by seahindeniz** [comment]
> Similarly, in the "Filters can be applied only to those reports that have been "loaded" line, "loaded" could be replaced with "fetched"

![image](https://user-images.githubusercontent.com/5789670/96874263-9a2ce380-147e-11eb-844f-7bd60d588875.png)

![image](https://user-images.githubusercontent.com/5789670/96874305-a44ee200-147e-11eb-9f4e-a8d8f74b1c0e.png)

**Comment by Tomboyish44** [comment]
Woah, Thanks a lot! 😄
