### ISSUE TITLE
Load more

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#296]
**Is your feature request related to a problem? Please describe.**
Não. Por padrão o antigo Moderar Tudo mostra 60 conteúdo por página, isso facilitava a análise de uma página a ser moderada em massa. 

**Describe the solution/idea you'd like**
Poderia ser possível definir a quantidade de conteúdo que queremos que o botão "load more" torne visível a cada clique ou aumentar esse número por padrão.

**Describe expected outcome from your solution**
![image](https://user-images.githubusercontent.com/39934266/96934943-1d573500-1491-11eb-971e-6c6f4926de86.png)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by seahindeniz** [comment]
![29af4d9c-fce7-44d0-b205-5225d74022fc](https://user-images.githubusercontent.com/5789670/97060309-9e025800-159b-11eb-88b9-51c8bb030500.gif)

This screenshot was taken on https//brainly.in 
The edge number "450" can be different on other sites
