### ISSUE TITLE
An "already moderated/deleted/confirmed" counter beside the "moderated", "failed" counters. 

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#297]
**Is your feature request related to a problem? Please describe.**

Yeah, while moderating content using the mass-moderate tool, the "moderated" counter includes the reports that were already deleted/moderated by other moderators.

Since the numbers shown refer to the moderations done using the mass-moderate tool by the user, it could be incorrect.

**Describe the solution/idea you'd like**

A counter that specifies the number of reports that have already been moderated, something like this;

![image](https://user-images.githubusercontent.com/68370357/97082128-f9c4f380-1624-11eb-9bf6-15a2917047d7.png)

**Describe expected outcome from your solution**

A way to know the number of reports that have already been moderated (or deleted, confirmed, reserved) after mass-moderating a set of reports.

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
![Screenshot_46](https://user-images.githubusercontent.com/5789670/97225676-ffb50300-17e3-11eb-9dbb-d181568437f7.png)
