### ISSUE TITLE
Filter reports

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#302]
**Describe the issue/bug:**
O filtro "Reporter user:" está retornando como "Reported user:"

**To Reproduce:**
1. Vá para https://brainly.com.br/question/add?reported-contents
2. Clique em "options"

3. Preencha o campo "Reporter user:"

**Screenshots [paste below, optional]:**

![filtro](https://user-images.githubusercontent.com/39934266/97816843-b266e480-1c6e-11eb-9282-12d8ad59df61.gif)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by seahindeniz** [comment]
Hi @Maxonvs 

Your GIF is very small for identifying characters that you use. I'll try to reproduce but in the meantime, do you mind sending a bigger version of that gif, please?

**Comment by Maxonvs** [comment]
@seahindeniz acho que ficou melhor, mas se precisar posso hospedar em vídeo. 

![Report](https://user-images.githubusercontent.com/39934266/97820345-265fb780-1c84-11eb-8d45-aa4606592340.gif)

**Comment by seahindeniz** [comment]
Thanks a lot, @Maxonvs
