### ISSUE TITLE
Yeni kullanıcı sayfası için eski sayfaya yönlendiren buton. 

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#306]
Eski kullanıcı sayfası

![Screenshot_20201104_173146](https://user-images.githubusercontent.com/62960189/98124187-e71fa980-1ec3-11eb-9193-fef8dca0fcd3.jpg)

Yeni kullanıcı sayfası

![IMG_20201104_173059](https://user-images.githubusercontent.com/62960189/98124200-edae2100-1ec3-11eb-98ec-84cd61ea83ae.jpg)

**Comment by seahindeniz** [comment]
This is how it will look like
![image](https://user-images.githubusercontent.com/5789670/100476649-2e7e0c00-30f7-11eb-8bd1-e8c135106262.png)
