### ISSUE TITLE
Düzenle panelinde çok fazla eylem yapıldığında geçmiş gözükmez. 

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#312]
Geçmiş kısmı çok olduğunda sayfa çok donar ve eylem yapamamıza yol açar. Buna çözüm bulunması bizim için çok iyi olacaktır. Örnek soru linki : https://eodev.com/gorev/18817778

**Comment by seahindeniz** [comment]
Hey @UgurhanKazanci61 

I have tried to increase the performance issue but so far, I could only delete some container elements from the log section and place a toggle button right next to date element to have some sort of a tree-like view

Here
![7c52b3ff-a25b-4499-857b-cf5bc500eed1](https://user-images.githubusercontent.com/5789670/100359860-3069a180-3009-11eb-919c-4246087a5d0d.gif)

This one is from the link that you've attached 
![1ba71a87-d415-4cf5-b1d7-db279ca3dc87](https://user-images.githubusercontent.com/5789670/100360274-c9002180-3009-11eb-9f51-35b4577644cb.gif)
