### ISSUE TITLE
"Delete All Comments" option in Mass-Manage Users

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#317]
A feature can be added that deletes all comments of the listed users at once.
![image](https://user-images.githubusercontent.com/47514611/100380352-bdbbee80-3027-11eb-950f-928aa573a655.png)

**Comment by remreozturk** [comment]
It may be like this 👇
![image](https://user-images.githubusercontent.com/73168853/101238035-73ed9b00-36ee-11eb-9dff-88f5b9445599.png)

**Comment by NisiDominus** [comment]
It may be like this 👇
![image](https://user-images.githubusercontent.com/47514611/101238105-eb232f00-36ee-11eb-80df-872cf6aceee9.png)

**Comment by seahindeniz** [comment]
Duplicate of #27 

This one has requested before so, I'm closing it and will continue over there
