### ISSUE TITLE
Both valid and invalid actions are treated as invalid actions while using the Inform Moderator feature

### ISSUE THREAD

**Issue by HarshSaini800** [seahindeniz/BrainlyTools_Extension#322]
**Describe the issue/bug:**
Both valid and invalid actions are treated as invalid actions while using the **Inform Moderator** feature

**To Reproduce:**
1. Tap the thumbs down button for one action and Thumbs Down for the other action.
2. Tap **Inform Moderator**. Both the validated and the invalidated action show up as invalid to inform the moderator. 
3. The result doesn't change even if you refresh the page.

**Screenshots:**

![image](https://user-images.githubusercontent.com/67321824/100498960-ec52da00-318b-11eb-9cf6-1c00a7bc3cde.png)
![image](https://user-images.githubusercontent.com/67321824/100498984-0b516c00-318c-11eb-92d9-e1a013d0e188.png)

https://brainly.in/profile/CoolestCat015-1426383

**Comment by seahindeniz** [comment]
Ah 😓 got it
