### ISSUE TITLE
Error in orientation of Special Ranks in User Content Page

### ISSUE THREAD

**Issue by HarshSaini800** [seahindeniz/BrainlyTools_Extension#328]
**Describe the issue/bug:**
Special Ranks appear slightly above the rest of the lines on the **User Content** Page

**To Reproduce:**
1. Visit **User Content** of any user with special ranks.
2. Tap any Question or Answer related to them

**Screenshots:**
![image](https://user-images.githubusercontent.com/67321824/100581073-197ac600-330d-11eb-9acd-18b84f1b4dcb.png)
![image](https://user-images.githubusercontent.com/67321824/100581102-25ff1e80-330d-11eb-9c7b-711de4fb4fb8.png)

**Comment by seahindeniz** [comment]
Can you share the page link please?
