### ISSUE TITLE
Extension doesn't  change bio when the input is empty

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#331]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/47514611/101606178-20dc5680-3a14-11eb-86d2-b713ec509603.gif)

**Comment by seahindeniz** [comment]
This issue related to Brainly. Brainly doesn't allow emptying your bio message however, I will try to add a workaround to clear the message anyway.

The solution I can think of at the moment is emptying the bio message by adding a [zero-width space](https://www.compart.com/en/unicode/U+200B) character to make it look like it's empty/cleared 🤷‍♂️
