### ISSUE TITLE
On the user's content view page, being able to delete the questions he answered

### ISSUE THREAD

**Issue by HydroXBR** [seahindeniz/BrainlyTools_Extension#339]
**Is your feature request related to a problem? Please describe.**
No. It is a suggestion for improvement.

**Describe the solution/idea you'd like**
On the user's content view page, being able to delete the questions he answered

**Describe expected outcome from your solution**
It would be very good if on the user's content viewing page, we could eliminate the questions he answered, as there are many users who answer questions with banter and banal, and this tool would be very useful, to help in moderating content and reducing reports. It would be similar to how to eliminate by selecting answers and questions.

**Your profile**
_https://brainly.com.br/app/profile/16367094_

Thanks from Brazil!

**Comment by seahindeniz** [comment]
I'm not sure if I understand you correctly 😓

Are you asking about a way to remove questions from the answers page?

Like this:
![image](https://user-images.githubusercontent.com/5789670/102669541-e6a34f80-419f-11eb-847f-505ed4e9182a.png)

**Comment by HydroXBR** [comment]
Yes that's right. But, as I saw in the print, it seems that I was wrong, I hadn't removed it through the questions, sorry. Thanks!

**Comment by HydroXBR** [comment]
Yes that's right. But, as I saw in the print, it seems that I was wrong, I hadn't removed it through the questions, sorry. Thanks!
