### ISSUE TITLE
Possível bug

### ISSUE THREAD

**Issue by EtinhoBR** [seahindeniz/BrainlyTools_Extension#342]
**Describe the issue/bug:**
Um possível problema que tenho a usar a extensão: Eu tenho a permissão de remover todas as tarefas de um usuário de vez, só que com a extensão ligada essa opção não aparece, somente quando eu desativo a extensão e recarrego o site

**To Reproduce:**
1. Abrir o perfil de algum usuário
2. Ir em "Mostrar mais informações"

**Screenshots [paste below, optional]:**
Sem a extensão:
![image](https://user-images.githubusercontent.com/76266607/102700818-89ef7580-422f-11eb-8f5a-3d19871785a2.png)

Com a extensão:
![image](https://user-images.githubusercontent.com/76266607/102700845-bb684100-422f-11eb-89ae-d08932cc77db.png)

https://brainly.com.br/perfil/EtinhoBR-13736288

**Comment by seahindeniz** [comment]
Hey @EtinhoBR 

I know and this behavior is intentional. It has requested by community managers, and it has introduced after #99 

To solve it out, your community manager needs to give you the ability to use content delete options on profile page.

**Comment by EtinhoBR** [comment]
Olá @seahindeniz 
O problema acaba de ser resolvido, obrigado :smile:
