### ISSUE TITLE
Real-time tracking for moderation status of a question

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#348]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution/idea you'd like**
The goal is to indicate on the home page and on other pages if the content is already being moderated. 

**Describe expected outcome from your solution**
Something similar to what already exists for the new "reported content (beta)" page.
![image](https://user-images.githubusercontent.com/64775524/103094933-34381600-45ff-11eb-9a0c-1e50623a2fea.png)

https://nosdevoirs.fr/profil/TomRh-578978

**Comment by seahindeniz** [comment]
Hey @tom-rh 

We can have this 🤔 Imagine someone reserves a ticket and that moderator will popup right next to the Moderate button

![52a8d636-32af-4bf8-b5bc-f8c47626afb6](https://user-images.githubusercontent.com/5789670/103319983-d6fbf480-4a44-11eb-9ea1-ab604540e70c.gif)

**Comment by tom-rh** [comment]
I have only one thing to say: **Wonderful!** 😮😍

This little animation is really nice too 👍

**Comment by seahindeniz** [comment]
Alrighty then, here is the feed version

![abb94c61-b984-4f52-a952-6bc153fd9442](https://user-images.githubusercontent.com/5789670/103354036-8bd0f880-4abb-11eb-8e1e-e5accb8bc6b4.gif)
