### ISSUE TITLE
Mass-Message sender

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#358]
**Is your feature request related to a problem? Please describe.**
A little bit. Sometimes the mass message tool shows one or more errors.

**Describe the solution/idea you'd like**
It would be interesting that when this happened the tool would show which ids the sending failed in, in order to we could repeat or check what's wrong.

![image](https://user-images.githubusercontent.com/39934266/103672022-1305ec80-4f52-11eb-8233-553965b29ca3.png)

https://brainly.com.br/perfil/badcsound-1110038

**Comment by NisiDominus** [comment]
Do you have your own ID on the list?

**Comment by Maxonvs** [comment]
> Do you have your own ID on the list?

I have  D:

**Comment by seahindeniz** [comment]
Ah, I think extension can just ignore the id number of sender 🤔
