### ISSUE TITLE
The fetch is reseted if clicks to change the page

### ISSUE THREAD

**Issue by Alphka** [seahindeniz/BrainlyTools_Extension#373]
**Describe the issue/bug:**
If the moderator clicks on a random page number, or switches to "comments" page, the fetch is reseted.

**To Reproduce:**
1. Go to [brainly.com.br/question/add?reported-contents](https://brainly.com.br/question/add?reported-contents)
2. Click in "Fetch all reports", then stop after a while
3. Click on a page number, or click in "Comments" button (changing the report reason/subject also works)

![Fetch_issue](https://user-images.githubusercontent.com/71673694/104092306-e576b700-5261-11eb-8aed-9630736daed2.gif)

[https://brainly.com.br/perfil/Alphka-14558160](https://brainly.com.br/perfil/Alphka-14558160)

**Comment by seahindeniz** [comment]
Hi

This is actually not a bug, it's an intentional behavior. Switching pages, resets cache and loads reports under that page number. If you click the fetch all reports button again, the page will fetch reports starting from that page to older reports

**Comment by Alphka** [comment]
Okay, but what if the moderator missclick some of those button, and lose 4+ hours of fetch?

**Comment by seahindeniz** [comment]
Well, 4 hours of fetch is most certainly unreliable.
Fetching means, you are downloading details of reports from Brainly and storing in background and then moderating. In 4 hours, lots of contents might get change and some of your time will be wasted even by starting to moderate those contents :eyes:

And also, extension can popup a warning message to warn user if they want to switch between filters/pages/report types in favor of not loosing cache by mistake
