### ISSUE TITLE
Add a banning section on the page of a question

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#377]
**Is your feature request related to a problem? Please describe.**

Feature is not linked to a problem. It is simply a matter of going faster to ban a spammer.

**Describe the solution/idea you'd like**

This new section could look like this:
![image](https://user-images.githubusercontent.com/64775524/104122721-0f55d980-5347-11eb-8602-59bc1c465a91.png)

We also need to retrieve this information in order to display it ✅
![image](https://user-images.githubusercontent.com/64775524/104122733-1da3f580-5347-11eb-836d-1f54081ec545.png)

**Describe expected outcome from your solution**

A ban section where each user participating in a question can be banned.

https://nosdevoirs.fr/profil/TomRh-578978

**Comment by seahindeniz** [comment]
Here is an early stage preview of the Users(_haven't decided the name yet_) section

![image](https://user-images.githubusercontent.com/5789670/104448842-bdaf8800-55ae-11eb-9188-60bac1edfab5.png)

When you click the button with three dots, it will open up a subsection that will contain the ban options.

Furthermore, we need to decide, what kind of detail/data/information we may need to see more from the Users section beside details of the currently given ban.
If anyone has a suggestion that will be useful to have, feel free to add here. We can discuss its functionality and will try to implement it

**Comment by tom-rh** [comment]
> Furthermore, we need to decide, what kind of detail/data/information we may need to see more from the Users section beside details of the currently given ban.
> If anyone has a suggestion that will be useful to have, feel free to add here. We can discuss its functionality and will try to implement it

For my part, I think it should be displayed for each profile :

- The number of warnings.
- If it is already banned now or not?

**Comment by CoolestCat015** [comment]
uwu

![Beside the User's Name](https://user-images.githubusercontent.com/67321824/104451748-f9a31700-55c7-11eb-950d-33173dc29fd1.png)
![Below Content and Above Log](https://user-images.githubusercontent.com/67321824/104451755-fad44400-55c7-11eb-9539-dd159180c95c.png)

**Comment by seahindeniz** [comment]
Hey @CoolestCat015 that's a cool request but, can you open a new issue for this one after we have the users section for question page? It's because your request is basically related to the moderate panel module, not the question page 😅

**Comment by seahindeniz** [comment]
This feature could also be a solution for #160. It may not solve the main issue, but it will meet the need
