### ISSUE TITLE
Privilege to remove users from the extension for Community leaders 

### ISSUE THREAD

**Issue by Happiestwriter012** [seahindeniz/BrainlyTools_Extension#38]
Privilege to remove users from the extension for Community leaders

( Please talk to Haezel mam too once)

**Comment by BrainlHaezel** [comment]
We don't need it because we already remove the moderator via moderation tools, which is the first line of defense, so let's keep it limited only to the admins. 

In case, the former is not working, then let's add this feature.

**Comment by Happiestwriter012** [comment]
We have asked for *Notice board* feature, and it will be visible to all extension users irrespective of they have moderating privs or not.

We thought to add announcements in notice boards and they will be visible to non mods too then ( if extension users aren't removed after leaving modship)

**Comment by seahindeniz** [comment]
@Happiestwriter012  To prevent this kind of problems, I've added a "restrictor" feature to the new Notice board. You guys can add texts for both, moderators and normal users seperately in the same content page.
I'll give you more information about this feature

**Comment by Happiestwriter012** [comment]
Sure :)
