### ISSUE TITLE
The content length filter is not working properly

### ISSUE THREAD

**Issue by Alphka** [seahindeniz/BrainlyTools_Extension#380]
**Describe the issue/bug:**
The "Content length" filter on Reported Contents page shows answers with more than 1000 characters, when its value is lower than 120 or 150 length.

**To Reproduce:** (Might not work always)
1. Go to [brainly.com.br/question/add?reported-contents](https://brainly.com.br/question/add?reported-contents)
2. Change the value of content length to "lower than 120"
3. Fetch some reports

After that you'll may be able to see answers that shouldn't be filtered

![Length_filter](https://user-images.githubusercontent.com/71673694/104139835-cfb1e080-538c-11eb-98fa-7d9febf6946e.gif)

[https://brainly.com.br/perfil/Alphka-14558160](https://brainly.com.br/perfil/Alphka-14558160)

**Comment by seahindeniz** [comment]
Hi @Alphka 

The filter works correctly but not the way you expect. The content length filter calculates only the preview/short version of the content that is visible in the queue. Brainly serves a short version of the real content and extension measures that data. Requesting a full content from Brainly for all fetched contents, may create noticeable delay on some devices that might have slow network or low RAM capacity. Some users can't afford this kind of workflow.

I can add a small informative text, that will give the user an idea of what should they expect from that filter
![image](https://user-images.githubusercontent.com/5789670/104170803-c10e0c80-5412-11eb-87b4-85a065288c95.png)
