### ISSUE TITLE
An ignore comment button/option beside comments to ignore them while deleting comments using the 'Delete All Comments' option.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#388]
**Is your feature request related to a problem? Please describe.**
Not really, but it'd be useful to have an option to ignore certain comments while using the 'Delete all comments' option to prevent valid comments from getting deleted amid a bunch of invalid comments.

**Describe the solution/idea you'd like**
An ignore button to ignore comments from being moderated while using the 'Delete All comments' option, like the ignore button in the reported contents page which allows ignoring reports while mass moderating.

![image](https://user-images.githubusercontent.com/68370357/104945358-a1608080-59de-11eb-88b0-c24a1ea3d6ca.png)

**Describe expected outcome from your solution**
Ability to ignore certain comments while moderating comments using the 'Delete All Comments' option.

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
Hi @Tomboyish44 thanks for the suggestion.

I have thought about adding an ignore button just like your example, but it may conflict with the visibility of action buttons and later than I decide placing it before the profile picture to be visible all the time without changing the structure of how quick action buttons are visible.

Here it is 
![6786dd6f-b531-4f00-b3e0-4e58165bba12](https://user-images.githubusercontent.com/5789670/106366511-6f8bda00-634d-11eb-8436-74d6f90b63d7.gif)

**Comment by ItzProgrammer** [comment]
Comments had been closed again in Brainly.in
