### ISSUE TITLE
Quick delete buttons don't appear in questions responses

### ISSUE THREAD

**Issue by HydroXBR** [seahindeniz/BrainlyTools_Extension#399]
**Describe the issue/bug:**
When we open a question, the **quick-delete buttons don't appear** on the answers, and the "Moderate" button doesn't lead to the moderation panel of the extension, but to the original Brainly panel.

**To Reproduce:**
1. Open a question normally, as if you were going to answer
2. Go to one of the answers

**Screenshots [paste below, optional]:**
![Task Brainly](https://user-images.githubusercontent.com/72590492/108521629-50280300-72a2-11eb-9515-860048de2de1.png)

https://brainly.com.br/app/profile/16367094

**Comment by tom-rh** [comment]
Same problem on my side.

This is the error in the console.

![image](https://user-images.githubusercontent.com/64775524/108629642-29fc9180-7461-11eb-98df-71be3fa1fd81.png)
