### ISSUE TITLE
New Personal Notes Not Saving

### ISSUE THREAD

**Issue by LukeG294** [seahindeniz/BrainlyTools_Extension#410]
**Describe the issue/bug:**
When messaging a user or on their profile page and creating a new personal note, it does not save upon re-entering the page. Previous notes can still be viewed.

**To Reproduce:**
1.  Visit a profile page: https://brainly.com/profile/user-userid
2. Type a personal note in the notes section 
![image](https://user-images.githubusercontent.com/62516707/113498223-e6fdf700-94bf-11eb-9aaf-f512d43f8e5b.png)
3. Refresh the page, the note is not saving.

https://user-images.githubusercontent.com/62516707/113498286-5b389a80-94c0-11eb-8ffb-0aca02f18ad9.mov

https://brainly.com/profile/LukeG1-16118329

**Comment by seahindeniz** [comment]
Hey @LukeG294, could you please check and confirm it has fixed for you?

**Comment by LukeG294** [comment]
Hi @seahindeniz, looks like this is working now after 7.23.4, thanks!
