### ISSUE TITLE
The Noticeboard isn't displayed on the moderation panel

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#413]
**Describe the issue/bug:**
All moderators except me have this problem.
For them, the Noticeboard isn't displayed on the moderation panel.

**To Reproduce:**
1. Be a moderator.

**Screenshots [paste below, optional]:**
Today, they have only this:
![image](https://user-images.githubusercontent.com/64775524/113787629-aad6ca80-973b-11eb-8d04-af46cb940469.png)

They should see this 2 options: (my view)
![image](https://user-images.githubusercontent.com/64775524/113787938-381a1f00-973c-11eb-9707-7ead5fde19c0.png)

https://nosdevoirs.fr/profil/TomRh-578978

**Comment by MarLakBrainlyPL** [comment]
In Poland we never had a Noticeboard :(
