### ISSUE TITLE
The extension isn't working/loading in. 

### ISSUE THREAD

**Issue by Tb-4-4** [seahindeniz/BrainlyTools_Extension#418]
**Describe the issue/bug:**
The extension isn't loading/working on different markets.

**To Reproduce:**
1. Go to https://brainly.in/
2. You'll be able to see that the extension isn't working

[Tried reinstalling, didn't work]

**Screenshots [paste below, optional]:**

Errors shown in the console:

![image](https://user-images.githubusercontent.com/68370357/117639716-d9fcb380-b1a1-11eb-989f-3c2defdcbdd2.png)

https://brainly.in/app/profile/2709968

**Comment by MarLakBrainlyPL** [comment]
Extension isn't working on brainly.pl too.

**Comment by crsheldon** [comment]
Brainly.com is facing the same problem!

**Comment by ahmadfauzialdi21** [comment]
now at **brainly.co.id** the extension is working again
time: 02.04p.m

**Comment by hashed17** [comment]
Facing the same problem at brainly.in and it is not yet resolved. I tried reinstalling the extension, yellow sign doesn't converts into green. Extension options creates some constant message " Please wait..". Kindly check this.
