### ISSUE TITLE
Quick delete buttons on question search 

### ISSUE THREAD

**Issue by Happiestwriter012** [seahindeniz/BrainlyTools_Extension#49]
Quick delete buttons on
https://brainly.in/app/ask?entry=top&q=Lorem+ipsum+dolor+sit+amet

**Comment by Happiestwriter012** [comment]
And can you add selective deletion too?

**Comment by Happiestwriter012** [comment]
@sahin.D

**Comment by seahindeniz** [comment]
@Happiestwriter012 Added https://github.com/seahindeniz/BrainlyTools_Extension/commit/c769f6c34407999203796dc250eb0486fe8205b6
