### ISSUE TITLE
View Notice Board

### ISSUE THREAD

**Issue by Greenrune113** [seahindeniz/BrainlyTools_Extension#66]
**Is your feature request related to a problem? Please describe.**
We have the notice board management permission in the extension, but all extension members cannot see the notice board without having the notice board management permission.

**Describe the solution you'd like**
I suggest we add in a "View Notice Board" permission in the extension, so you don't have to have the notice board management permission to view it.

**Comment by seahindeniz** [comment]
Hey @Greenrune113 

If the notice board managers would not add anything on the board, extension will not show this option 
![image](https://user-images.githubusercontent.com/5789670/58883150-7f6d9980-86e6-11e9-8f85-12e73fe06ca2.png)
to the extension users to keep the list smaller by not showing it. 

But if you add something in here
![image](https://user-images.githubusercontent.com/5789670/58883051-4e8d6480-86e6-11e9-94d7-dd5bf7671503.png)

This will change the behaviour and users will be able to see the notice board
