### ISSUE TITLE
Mini mod panel in the abuses page 

### ISSUE THREAD

**Issue by Happiestwriter012** [seahindeniz/BrainlyTools_Extension#78]
https://brainly.in/abuses/today

What i say is, don't show *only* the reported content to moderator. Show the entire thing ( question, answer) to moderators like in moderate all ( after we click on specific thing) and highlight reported content as red as like in normal taskplayer . From there, Moderator will moderate the contents

**Comment by seahindeniz** [comment]
This page is sync with moderate all and reported contents page. Since contents can also moderate through those pages, there is no point in having an extra page either. I'm closing the request
