### ISSUE TITLE
Place to handle vulgar users

### ISSUE THREAD

**Issue by KaiDrolop** [seahindeniz/BrainlyTools_Extension#95]
Hello Sahin , these days a lot of vulgar users are posting about 10 000 vulgar questions per day.
Thanks to your program that delete questions with vulgar words , a lot of vulgar questions are deleted.

This is what I suggest to take an appropriate action about these users ; 

If the user got 5 vulgar questions deleted ,  he is automatically added in a list which Spam Fighters or Leader will take an appropriate action .  It's a kind of "simple moderation " but for vulgar users with more than 5 warnings given by your program that detect vulgar words. Thank you.

**Comment by seahindeniz** [comment]
Thanks Kai for suggesting that. I already finished that up and soon its ready to be deployed. Community managers can take actions on spammers accounts which has dealt by the service

I'm going to close this issue since it has resolved
