### ISSUE TITLE
Bug while deleting account

### ISSUE THREAD

**Issue by KaiDrolop** [seahindeniz/BrainlyTools_Extension#96]
Hello sahin , I have a little issue : 
While I am deleting an account with extension  it's written  " Content Uploading 100" and even If I click on Delete it doesn't work. Img 1

 Also (suggestion ) when we finish to upluad an image evidence , it will be good  if a green tick appear .  IMG2
![Capture](https://user-images.githubusercontent.com/50515478/76109005-b0b82480-5fec-11ea-80c1-0443345731fb.PNG)
![Capture](https://user-images.githubusercontent.com/50515478/76109067-ccbbc600-5fec-11ea-9f13-602163e60c08.PNG)

**Comment by seahindeniz** [comment]
Solved
